# Generated by Django 3.1 on 2020-09-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typical_chest_pain', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('age', models.IntegerField()),
                ('dm', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('ht', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('fh', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('tg', models.IntegerField()),
                ('k', models.FloatField()),
                ('region_rwma', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=15)),
                ('bbb', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('tinversion', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('fbs', models.IntegerField()),
                ('esr', models.IntegerField()),
                ('ef_tte', models.IntegerField()),
                ('dlp', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('diastolic_murmur', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
            ],
        ),
    ]
